# Generated by Django 5.0.6 on 2024-08-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_publicacion_creador'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
